sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install bundler
  - gem install jbundler
jdk:
  - oraclejdk8
rvm:
  - jruby-9.1.5.0
env:
  - JRUBY_OPTS=--debug

script: bundle exec jbundle install

branches:
  only:
    - public
